[package]
name = "bottles"
version = "0.1.1"
authors = ["Marcin Szymczak <marszym@pm.me>"]
edition = "2018"
license = "MIT"
description = "An enum-less typed message passing mechanism"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
